### PR TITLE
done workshop

### PR DESCRIPTION
**Pull request by chrisshino**

### CODE REVIEW

**Review by orangesmartie92 — CHANGES_REQUESTED** [review]
exercise 1. question 5 missing

**Comment by chrisshino** [comment]
Please recheck, number 5 is there and is passing the test suite. 

Thanks

**Comment by orangesmartie92** [comment]
@chrisshino sorry about that I meant Exercise2 Question 5!

**Comment by chrisshino** [comment]
Thanks! All updated and pushed to the repo

**Pull request closed without merging**
