### PR TITLE
JS-1 workshop finished

### PR DESCRIPTION
**Pull request by vishal-handa**

### CODE REVIEW

**Review by orangesmartie92 — CHANGES_REQUESTED** [review]
Please Re-do and re-test 1, 4, 5, 7, 10 because those are failing.

**Comment by vishal-handa** [comment]
Sorry, but I don't understand the issue with other exercises. I have edited ex5, but the others are running properly.

**Comment by orangesmartie92** [comment]
@vishal-handa . Please do
```
yarn test exercise-\\d\\D exercise-10.test
```
You will see that exercise 1 is failing because you've comment out the entire thing. 
Exercise 4, 7 and 10 are not receiving the expected results.

thanks!

**Comment by vishal-handa** [comment]
I just saw the master exercise1, and the entire thing is a comment with back ticks. I tried removing it but the VS Code gave me 10 errors. 
Also, I am not able to do the yarn test. I have the extension install, and when i run it I get "yarn : The term 'yarn' is not recognized as the name of a cmdlet, function, script file, or operable program."

Is there a way that this can be resolved over a zoom call during the workshop time? There is one tomorrow.

**Pull request closed without merging**
